"use client";
import {useEffect,useState} from "react";
import {supabase} from "../lib/supabaseClient";
const input={width:"100%",padding:"10px 12px",border:"1px solid #dde1e6",borderRadius:8};
const grid={display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10};
export default function GovernanceBoardPanel({schoolId}){
 const year=new Date().getFullYear(),[terms,setTerms]=useState([]),[members,setMembers]=useState([]),[selected,setSelected]=useState(""),[error,setError]=useState("");
 const[term,setTerm]=useState({title:`${year} Governing Board`,governance_year:year,term_start:`${year}-01-01`,term_end:`${year}-12-31`,status:"planned",notes:""});
 const[member,setMember]=useState({full_name:"",board_role:"member",representing_group:"community",appointment_method:"",appointment_date:"",service_start:"",service_end:"",phone:"",email:"",national_id:"",qualifications_or_expertise:"",declaration_of_interests:"",conflict_notes:"",background_check_status:"not_requested",status:"active"});
 async function load(){const[a,b]=await Promise.all([supabase.from("governance_terms").select("*").eq("school_id",schoolId).order("governance_year",{ascending:false}),supabase.from("governance_members").select("*").eq("school_id",schoolId).order("full_name")]);setTerms(a.data||[]);setMembers(b.data||[]);if(!selected&&a.data?.length)setSelected(a.data[0].id);if(a.error||b.error)setError(a.error?.message||b.error?.message)}
 useEffect(()=>{load()},[schoolId]);
 async function createTerm(){if(!term.title.trim()||!term.term_start||!term.term_end)return setError("Enter a board title and dates.");const{data,error}=await supabase.from("governance_terms").insert({school_id:schoolId,...term,governance_year:Number(term.governance_year)}).select().single();if(error)setError(error.message);else{setSelected(data.id);await load()}}
 async function addMember(){if(!selected||!member.full_name.trim()||!member.service_start)return setError("Select a term and enter member name and service start.");const{error}=await supabase.from("governance_members").insert({school_id:schoolId,governance_term_id:selected,...member,appointment_date:member.appointment_date||null,service_end:member.service_end||null});if(error)setError(error.message);else{setMember({...member,full_name:"",appointment_method:"",appointment_date:"",service_start:"",service_end:"",phone:"",email:"",national_id:"",qualifications_or_expertise:"",declaration_of_interests:"",conflict_notes:""});await load()}}
 async function status(id,value){const{error}=await supabase.from("governance_terms").update({status:value,updated_at:new Date().toISOString()}).eq("id",id);if(error)setError(error.message);else await load()}
 const selectedTerm=terms.find(x=>x.id===selected),rows=members.filter(x=>x.governance_term_id===selected);
 return <div>{error?<p className="error">{error}</p>:null}<div className="card" style={{marginBottom:18}}><h3 style={{marginTop:0}}>Create governing board term</h3><div style={grid}><input style={input} value={term.title} onChange={e=>setTerm(x=>({...x,title:e.target.value}))}/><input type="number" style={input} value={term.governance_year} onChange={e=>setTerm(x=>({...x,governance_year:e.target.value}))}/><input type="date" style={input} value={term.term_start} onChange={e=>setTerm(x=>({...x,term_start:e.target.value}))}/><input type="date" style={input} value={term.term_end} onChange={e=>setTerm(x=>({...x,term_end:e.target.value}))}/></div><textarea style={{...input,minHeight:70,marginTop:10}} placeholder="Term notes" value={term.notes} onChange={e=>setTerm(x=>({...x,notes:e.target.value}))}/><button onClick={createTerm} style={{marginTop:10}}>Create board term</button></div>
 {terms.length?<div className="card" style={{marginBottom:18}}><select style={input} value={selected} onChange={e=>setSelected(e.target.value)}>{terms.map(x=><option key={x.id} value={x.id}>{x.governance_year} - {x.title} - {x.status}</option>)}</select>{selectedTerm?<div style={{display:"flex",gap:8,marginTop:10}}><button onClick={()=>status(selectedTerm.id,"active")}>Mark active</button><button className="ghost" onClick={()=>status(selectedTerm.id,"completed")}>Mark completed</button></div>:null}</div>:null}
 {selectedTerm?<><div className="card" style={{marginBottom:18}}><h3 style={{marginTop:0}}>Add board member</h3><div style={grid}>{["full_name","appointment_method","phone","email","national_id"].map(k=><input key={k} style={input} placeholder={k.replaceAll("_"," ")} value={member[k]} onChange={e=>setMember(x=>({...x,[k]:e.target.value}))}/>) }
 <select style={input} value={member.board_role} onChange={e=>setMember(x=>({...x,board_role:e.target.value}))}>{["chairperson","vice_chairperson","secretary","treasurer","member","ex_officio"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><select style={input} value={member.representing_group} onChange={e=>setMember(x=>({...x,representing_group:e.target.value}))}>{["parents","staff","community","church","owner","local_authority","ministry","other"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><input type="date" style={input} value={member.appointment_date} onChange={e=>setMember(x=>({...x,appointment_date:e.target.value}))}/><input type="date" style={input} value={member.service_start} onChange={e=>setMember(x=>({...x,service_start:e.target.value}))}/><input type="date" style={input} value={member.service_end} onChange={e=>setMember(x=>({...x,service_end:e.target.value}))}/></div><textarea style={{...input,minHeight:70,marginTop:10}} placeholder="Qualifications or expertise" value={member.qualifications_or_expertise} onChange={e=>setMember(x=>({...x,qualifications_or_expertise:e.target.value}))}/><textarea style={{...input,minHeight:70,marginTop:10}} placeholder="Declaration of interests" value={member.declaration_of_interests} onChange={e=>setMember(x=>({...x,declaration_of_interests:e.target.value}))}/><button onClick={addMember} style={{marginTop:10}}>Add board member</button></div><table><thead><tr><th>Member</th><th>Role</th><th>Represents</th><th>Service</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.full_name}</strong><div className="muted">{x.email||x.phone||""}</div></td><td>{x.board_role.replaceAll("_"," ")}</td><td>{String(x.representing_group||"-").replaceAll("_"," ")}</td><td>{x.service_start} to {x.service_end||"-"}</td><td>{x.status}</td></tr>)}</tbody></table></>:null}</div>
}
