"use client";
import {useEffect,useState} from "react";
import {supabase} from "../lib/supabaseClient";

const input={width:"100%",padding:"10px 12px",border:"1px solid #dde1e6",borderRadius:8};
const grid={display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10};

export default function PersonnelPanel({schoolId}){
  const[people,setPeople]=useState([]),[selected,setSelected]=useState(""),[tab,setTab]=useState("overview"),[error,setError]=useState("");
  const[profile,setProfile]=useState({personnel_type:"teacher",full_name:"",date_of_birth:"",national_id:"",employee_number:"",position:"",department:"",employment_type:"permanent",employment_start:"",professional_registration_number:"",professional_registration_body:"",professional_registration_expiry:"",phone:"",email:"",address:""});
  const[q,setQ]=useState({qualification_type:"degree",qualification_name:"",field_of_study:"",institution:"",country:"",start_year:"",graduation_year:"",qualification_number:"",verification_status:"unverified",document_reference:""});
  const[job,setJob]=useState({employer:"",job_title:"",start_date:"",end_date:"",reason_for_leaving:"",reference_name:"",reference_phone:"",reference_email:"",verification_status:"unverified"});
  const[union,setUnion]=useState({union_name:"",membership_number:"",joined_on:"",ended_on:"",status:"active"});
  const[vet,setVet]=useState({police_clearance_status:"not_requested",police_report_reference:"",police_report_issue_date:"",police_report_expiry_date:"",conviction_disclosed:false,offence_description:"",conviction_year:"",court_or_jurisdiction:"",sentence:"",sentence_served:"",suitability_decision:"pending",decision_notes:""});
  const[details,setDetails]=useState({q:[],jobs:[],unions:[],vetting:[]});

  async function load(){const{data,error}=await supabase.from("personnel_profiles").select("*").eq("school_id",schoolId).order("full_name");setPeople(data||[]);if(error)setError(error.message)}
  async function loadDetails(id){if(!id){setDetails({q:[],jobs:[],unions:[],vetting:[]});return}const[a,b,c,d]=await Promise.all([
    supabase.from("personnel_qualifications").select("*").eq("personnel_id",id),
    supabase.from("personnel_employment_history").select("*").eq("personnel_id",id),
    supabase.from("personnel_union_memberships").select("*").eq("personnel_id",id),
    supabase.from("personnel_vetting_records").select("*").eq("personnel_id",id)
  ]);setDetails({q:a.data||[],jobs:b.data||[],unions:c.data||[],vetting:d.data||[]});if(a.error||b.error||c.error||d.error)setError(a.error?.message||b.error?.message||c.error?.message||d.error?.message)}
  useEffect(()=>{load()},[schoolId]);useEffect(()=>{loadDetails(selected)},[selected]);
  function age(d){if(!d)return"-";const b=new Date(d),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))a--;return a}
  async function create(){if(!profile.full_name.trim())return setError("Enter the full name.");const{data,error}=await supabase.from("personnel_profiles").insert({school_id:schoolId,...profile,date_of_birth:profile.date_of_birth||null,employment_start:profile.employment_start||null,professional_registration_expiry:profile.professional_registration_expiry||null}).select().single();if(error)setError(error.message);else{await load();setSelected(data.id)}}
  async function add(table,payload,reset){if(!selected)return setError("Select a personnel record first.");const{error}=await supabase.from(table).insert({school_id:schoolId,personnel_id:selected,...payload});if(error)setError(error.message);else{reset();await loadDetails(selected)}}
  const person=people.find(x=>x.id===selected);

  return <div>{error?<p className="error">{error}</p>:null}
    <div className="card" style={{marginBottom:18}}><h3 style={{marginTop:0}}>Create personnel record</h3><div style={grid}>
      <select style={input} value={profile.personnel_type} onChange={e=>setProfile(x=>({...x,personnel_type:e.target.value}))}><option value="teacher">Teacher</option><option value="staff">Staff</option><option value="contractor">Contractor</option><option value="other">Other</option></select>
      {["full_name","national_id","employee_number","position","department","phone","email","professional_registration_number","professional_registration_body"].map(k=><input key={k} style={input} placeholder={k.replaceAll("_"," ")} value={profile[k]} onChange={e=>setProfile(x=>({...x,[k]:e.target.value}))}/>)}
      <input type="date" style={input} value={profile.date_of_birth} onChange={e=>setProfile(x=>({...x,date_of_birth:e.target.value}))}/><input type="date" style={input} value={profile.employment_start} onChange={e=>setProfile(x=>({...x,employment_start:e.target.value}))}/><input type="date" style={input} value={profile.professional_registration_expiry} onChange={e=>setProfile(x=>({...x,professional_registration_expiry:e.target.value}))}/>
    </div><textarea style={{...input,minHeight:70,marginTop:10}} placeholder="Address" value={profile.address} onChange={e=>setProfile(x=>({...x,address:e.target.value}))}/><button onClick={create} style={{marginTop:10}}>Create personnel record</button></div>
    <div className="card" style={{marginBottom:18}}><select style={input} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select personnel</option>{people.map(x=><option key={x.id} value={x.id}>{x.full_name} - {x.personnel_type}</option>)}</select>{person?<p><strong>{person.full_name}</strong> - Age {age(person.date_of_birth)} - Registration {person.professional_registration_number||"not recorded"}</p>:null}</div>
    {person?<><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:16}}>{[["overview","Overview"],["q","Qualifications"],["jobs","Employment history"],["unions","Trade union"],["vetting","Restricted vetting"]].map(([v,l])=><button key={v} className={tab===v?"":"ghost"} onClick={()=>setTab(v)}>{l}</button>)}</div>
      {tab==="overview"?<div className="card"><table><tbody>{[["Full name",person.full_name],["Date of birth",person.date_of_birth||"-"],["Age",age(person.date_of_birth)],["National ID",person.national_id||"-"],["Employee number",person.employee_number||"-"],["Position",person.position||"-"],["Professional number",person.professional_registration_number||"-"]].map(([a,b])=><tr key={a}><th>{a}</th><td>{b}</td></tr>)}</tbody></table></div>:null}
      {tab==="q"?<Simple title="Add qualification" form={q} setForm={setQ} keys={["qualification_name","field_of_study","institution","country","start_year","graduation_year","qualification_number","document_reference"]} onSave={()=>add("personnel_qualifications",{...q,start_year:q.start_year?Number(q.start_year):null,graduation_year:q.graduation_year?Number(q.graduation_year):null},()=>setQ({...q,qualification_name:"",field_of_study:"",institution:"",start_year:"",graduation_year:"",qualification_number:"",document_reference:""}))} rows={details.q} cols={[["qualification_name","Qualification"],["institution","Institution"],["graduation_year","Year"],["verification_status","Verification"]]}/>:null}
      {tab==="jobs"?<Simple title="Add previous employment" form={job} setForm={setJob} keys={["employer","job_title","start_date","end_date","reason_for_leaving","reference_name","reference_phone","reference_email"]} onSave={()=>add("personnel_employment_history",{...job,start_date:job.start_date||null,end_date:job.end_date||null},()=>setJob({...job,employer:"",job_title:"",start_date:"",end_date:"",reason_for_leaving:"",reference_name:"",reference_phone:"",reference_email:""}))} rows={details.jobs} cols={[["employer","Employer"],["job_title","Position"],["start_date","Start"],["end_date","End"]]}/>:null}
      {tab==="unions"?<Simple title="Add trade union membership" form={union} setForm={setUnion} keys={["union_name","membership_number","joined_on","ended_on"]} onSave={()=>add("personnel_union_memberships",{...union,joined_on:union.joined_on||null,ended_on:union.ended_on||null},()=>setUnion({...union,union_name:"",membership_number:"",joined_on:"",ended_on:""}))} rows={details.unions} cols={[["union_name","Union"],["membership_number","Membership"],["joined_on","Joined"],["status","Status"]]}/>:null}
      {tab==="vetting"?<div><div style={{padding:12,background:"#fff3cd",borderRadius:10,marginBottom:14}}>Restricted information. Limit access to authorised school leadership and HR personnel.</div><Simple title="Police clearance and suitability" form={vet} setForm={setVet} keys={["police_report_reference","police_report_issue_date","police_report_expiry_date","offence_description","conviction_year","court_or_jurisdiction","sentence","decision_notes"]} onSave={()=>add("personnel_vetting_records",{...vet,police_report_issue_date:vet.police_report_issue_date||null,police_report_expiry_date:vet.police_report_expiry_date||null,conviction_year:vet.conviction_year?Number(vet.conviction_year):null,sentence_served:vet.sentence_served===""?null:vet.sentence_served==="yes",decision_at:new Date().toISOString()},()=>{})} rows={details.vetting} cols={[["police_clearance_status","Clearance"],["conviction_disclosed","Conviction"],["suitability_decision","Decision"],["created_at","Recorded"]]}/></div>:null}
    </>:null}
  </div>
}
function Simple({title,form,setForm,keys,onSave,rows,cols}){return <div><div className="card" style={{marginBottom:18}}><h3 style={{marginTop:0}}>{title}</h3><div style={grid}>{keys.map(k=><input key={k} type={k.includes("date")||["start_date","end_date","joined_on","ended_on"].includes(k)?"date":"text"} style={input} placeholder={k.replaceAll("_"," ")} value={form[k]??""} onChange={e=>setForm(x=>({...x,[k]:e.target.value}))}/>)}</div><button onClick={onSave} style={{marginTop:10}}>Save</button></div><table><thead><tr>{cols.map(([,l])=><th key={l}>{l}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{cols.map(([k])=><td key={k}>{typeof r[k]==="boolean"?(r[k]?"Yes":"No"):(String(r[k]??"-").slice(0,k==="created_at"?10:100))}</td>)}</tr>)}</tbody></table></div>}
